#!/usr/bin/env python3
import os
from pathlib import Path

# ---------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------

ROOT = Path("vim")
SECTIONS = [
    "abstract_intro_section-i",
    "section-ii_harmonic_stabilizer",
    "section-iii_bliss_state",
    "section-iv_balance_coefficient",
    "section-v_control_architecture",
    "section-vi_topological_dissonance",
    "section-vii_flux_dynamics",
    "section-viii_sages_integration",
    "section-ix_safety_constraints",
    "section-x_conclusion"
]

# ---------------------------------------------------------
# DIRECTORY CREATION
# ---------------------------------------------------------

DIRS = [
    ROOT,
    ROOT / "sections",
    ROOT / "figures",
    ROOT / "simulation",
    ROOT / "build"
]

for d in DIRS:
    if not d.exists():
        print(f"[+] Creating directory: {d}")
        d.mkdir(parents=True, exist_ok=True)
    else:
        print(f"[=] Directory exists: {d}")

# ---------------------------------------------------------
# MAIN LATEX FILE
# ---------------------------------------------------------

main_tex = ROOT / "main.tex"

if not main_tex.exists():
    print(f"[+] Creating main.tex")
    with open(main_tex, "w") as f:
        f.write(r"""\documentclass[11pt]{article}

\usepackage{amsmath, amssymb}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{geometry}
\geometry{margin=1in}

\title{Vacuum Impedance Matching and the Theory of Balance}
\author{Ross A. Edwards \\ Aurphyx LLC}
\date{\today}

\begin{document}
\maketitle
\tableofcontents
\newpage
""")

        for s in SECTIONS:
            f.write(f"\\input{{sections/{s}.tex}}\n")

        f.write(r"""
\end{document}
""")
else:
    print(f"[=] main.tex exists, skipping.")

# ---------------------------------------------------------
# SECTION FILES
# ---------------------------------------------------------

for name in SECTIONS:
    filename = ROOT / "sections" / f"{name}.tex"
    if filename.exists():
        print(f"[=] Skipping existing section: {filename}")
        continue

    print(f"[+] Creating section file: {filename}")
    with open(filename, "w") as f:
        f.write(f"% {name.replace('_', ' ').title()}\n")
        f.write("% Auto-generated by vim_build_scaffold.py\n\n")
        f.write("\\section{}\n\n")
        f.write("% Write content here.\n")

# ---------------------------------------------------------
# SIMULATION README
# ---------------------------------------------------------

sim_readme = ROOT / "simulation" / "README.md"
if not sim_readme.exists():
    print(f"[+] Creating simulation README")
    with open(sim_readme, "w") as f:
        f.write("# VIM Simulation Scripts\n")
        f.write("Simulation modules for Vacuum Impedance Matching.\n")
else:
    print("[=] Simulation README exists.")

# ---------------------------------------------------------
# BUILD SCRIPT
# ---------------------------------------------------------

build_script = ROOT / "build_vim.py"

if not build_script.exists():
    print(f"[+] Creating build_vim.py")
    with open(build_script, "w") as f:
        f.write("""#!/usr/bin/env python3
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent
MAIN = ROOT / "main.tex"
OUT = ROOT / "build"

def build():
    print("[+] Building VIM thesis...")
    cmd = ["latexmk", "-pdf", "-interaction=nonstopmode", "-output-directory=" + str(OUT), str(MAIN)]
    subprocess.run(cmd)
    print("[✓] Build complete.")

if __name__ == "__main__":
    build()
""")
else:
    print("[=] build_vim.py exists.")

# ---------------------------------------------------------
# MAKEFILE
# ---------------------------------------------------------

makefile = ROOT / "Makefile"

if not makefile.exists():
    print(f"[+] Creating Makefile")
    with open(makefile, "w") as f:
        f.write("""all:
\tlatexmk -pdf -interaction=nonstopmode -output-directory=build main.tex

clean:
\trm -rf build/*

watch:
\tlatexmk -pdf -pvc -interaction=nonstopmode -output-directory=build main.tex
""")
else:
    print("[=] Makefile exists.")

print("\n[✓] VIM thesis scaffold created successfully.")