//! C# Code Generator

use anyhow::Result;
use crate::{
    ast::*,
    core::context::TransmutationContext,
};

pub struct CSharpGenerator;

impl CSharpGenerator {
    pub fn new() -> Self {
        Self
    }
    
    pub fn generate_code(&self, ast: &UniversalAst, _context: &TransmutationContext) -> Result<String> {
        let mut code = String::new();
        
        code.push_str("// Generated by FUTE - Fuxyez Universal Transmutation Engine\n\n");
        code.push_str("using System;\n");
        code.push_str("using System.Threading.Tasks;\n\n");
        
        self.generate_node(&ast.root, &mut code, 0);
        
        Ok(code)
    }
    
    fn generate_node(&self, node: &AstNode, code: &mut String, indent: usize) {
        let indent_str = "    ".repeat(indent);
        
        match node {
            AstNode::Module { items, .. } => {
                for item in items {
                    self.generate_node(item, code, indent);
                }
            }
            
            AstNode::Class { name, fields, methods, base_class, visibility } => {
                let vis = self.visibility_str(*visibility);
                let base = if let Some(b) = base_class {
                    format!(" : {}", b)
                } else {
                    String::new()
                };
                
                code.push_str(&format!("{}{} class {}{}\n", indent_str, vis, name, base));
                code.push_str(&format!("{}{{\n", indent_str));
                
                for field in fields {
                    let field_vis = self.visibility_str(field.visibility);
                    code.push_str(&format!("{}    {} {} {};\n",
                        indent_str, field_vis,
                        self.type_str(&field.ty),
                        field.name));
                }
                
                if !fields.is_empty() && !methods.is_empty() {
                    code.push('\n');
                }
                
                for method in methods {
                    self.generate_node(method, code, indent + 1);
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
            
            AstNode::Function { name, params, return_type, body, is_async, visibility } => {
                let vis = self.visibility_str(*visibility);
                let asyncness = if *is_async { "async " } else { "" };
                
                let params_str = params.iter()
                    .map(|p| format!("{} {}", self.type_str(&p.ty), p.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                
                let return_str = if let Some(ty) = return_type {
                    if *is_async {
                        format!("Task<{}>", self.type_str(ty))
                    } else {
                        self.type_str(ty)
                    }
                } else if *is_async {
                    "Task".to_string()
                } else {
                    "void".to_string()
                };
                
                code.push_str(&format!("{}{}{}{} {}({})\n",
                    indent_str, vis, asyncness, return_str, name, params_str));
                code.push_str(&format!("{}{{\n", indent_str));
                
                if body.is_empty() {
                    code.push_str(&format!("{}    // TODO: Implement\n", indent_str));
                } else {
                    for stmt in body {
                        self.generate_node(stmt, code, indent + 1);
                    }
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
            
            _ => {}
        }
    }
    
    fn visibility_str(&self, vis: Visibility) -> &'static str {
        match vis {
            Visibility::Public => "public",
            Visibility::Private => "private",
            Visibility::Protected => "protected",
            Visibility::Internal => "internal",
        }
    }
    
    fn type_str(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "int".to_string(),
            Type::Float => "double".to_string(),
            Type::String => "string".to_string(),
            Type::Bool => "bool".to_string(),
            Type::Void => "void".to_string(),
            Type::Named(n) => n.clone(),
            Type::Array(inner) => format!("{}[]", self.type_str(inner)),
            Type::Option(inner) => format!("{}?", self.type_str(inner)),
            _ => "object".to_string(),
        }
    }
}

impl Default for CSharpGenerator {
    fn default() -> Self {
        Self::new()
    }
}