//! Fuxyez Symbiotic Code Generator
//! 
//! Generates beautiful symbiotic Fuxyez code from Universal AST
//! 
//! Every line of generated code represents a bridge between languages,
//! a harmonious expression of multi-paradigm thinking.

use anyhow::Result;
use crate::{
    ast::*,
    core::context::TransmutationContext,
};

pub struct FuxyezCodegen {
    indent_size: usize,
}

impl FuxyezCodegen {
    pub fn new() -> Self {
        Self {
            indent_size: 4,
        }
    }
    
    /// Generate symbiotic Fuxyez code from Universal AST
    pub fn generate(&self, ast: &UniversalAst, _context: &TransmutationContext) -> Result<String> {
        let mut code = String::new();
        
        // Add symbiotic header
        code.push_str("// ═══════════════════════════════════════════════════════\n");
        code.push_str("// 🌐 SYMBIOTIC CODE - Generated by FUTE\n");
        code.push_str("// 💎 Fuxyez Universal Transmutation Engine\n");
        code.push_str("// 🔗 Where Languages Live in Harmony\n");
        code.push_str("// ═══════════════════════════════════════════════════════\n\n");
        
        // Generate imports for symbiotic runtime
        code.push_str("use fuxrt::symbiosis::*;\n");
        code.push_str("use fuxrt::lattice::Lattice;\n");
        code.push_str("use fuxrt::sigil::Sigil;\n");
        code.push_str("use fuxrt::ritual::Ritual;\n\n");
        
        // Generate symbiotic code
        self.generate_node(&ast.root, &mut code, 0);
        
        Ok(code)
    }
    
    // ... rest of implementation stays similar but with symbiotic comments
}
    fn generate_node(&self, node: &AstNode, code: &mut String, indent: usize) {
        let indent_str = " ".repeat(indent * self.indent_size);
        
        match node {
            AstNode::Module { name, items } => {
                if name != "root" {
                    code.push_str(&format!("{}ritual {} {{\n", indent_str, name));
                }
                
                for item in items {
                    self.generate_node(item, code, if name == "root" { indent } else { indent + 1 });
                }
                
                if name != "root" {
                    code.push_str(&format!("{}}}\n\n", indent_str));
                }
            }
            
            AstNode::Function { name, params, return_type, body, is_async, visibility } => {
                let vis = self.visibility_keyword(*visibility);
                let asyncness = if *is_async { "weave " } else { "" };
                
                let is_ritual = name.starts_with("ritual_");
                let is_sigil = name.starts_with("sigil_");
                
                let keyword = if is_ritual {
                    "ritual"
                } else if is_sigil {
                    "sigil"
                } else {
                    "sigil" // Default to sigil
                };
                
                let clean_name = name
                    .strip_prefix("ritual_")
                    .or_else(|| name.strip_prefix("sigil_"))
                    .unwrap_or(name);
                
                let params_str = params.iter()
                    .map(|p| format!("{}: {}", p.name, self.type_to_fuxyez(&p.ty)))
                    .collect::<Vec<_>>()
                    .join(", ");
                
                let return_str = if let Some(ty) = return_type {
                    format!(" -> {}", self.type_to_fuxyez(ty))
                } else {
                    String::new()
                };
                
                code.push_str(&format!("{}{}{}{} {}({}){} {{\n",
                    indent_str, vis, asyncness, keyword, clean_name, params_str, return_str));
                
                if body.is_empty() {
                    code.push_str(&format!("{}    collapse {{}}\n", indent_str));
                } else {
                    for stmt in body {
                        self.generate_node(stmt, code, indent + 1);
                    }
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
use anyhow::Result;
use crate::{
    ast::*,
    core::context::TransmutationContext,
};

pub struct FuxyezCodegen {
    indent_size: usize,
}

impl FuxyezCodegen {
    pub fn new() -> Self {
        Self {
            indent_size: 4,
        }
    }
    
    /// Generate Fuxyez code from Universal AST
    pub fn generate(&self, ast: &UniversalAst, _context: &TransmutationContext) -> Result<String> {
        let mut code = String::new();
        
        // Add header
        code.push_str("// ═══════════════════════════════════════════════════════\n");
        code.push_str("// Generated by FUTE - Fuxyez Universal Transmutation Engine\n");
        code.push_str("// ═══════════════════════════════════════════════════════\n\n");
        
        // Generate imports
        code.push_str("use fuxrt::prelude::*;\n");
        code.push_str("use fuxrt::lattice::Lattice;\n");
        code.push_str("use fuxrt::sigil::Sigil;\n");
        code.push_str("use fuxrt::ritual::Ritual;\n\n");
        
        // Generate code
        self.generate_node(&ast.root, &mut code, 0);
        
        Ok(code)
    }
    
    fn generate_node(&self, node: &AstNode, code: &mut String, indent: usize) {
        let indent_str = " ".repeat(indent * self.indent_size);
        
        match node {
            AstNode::Module { name, items } => {
                if name != "root" {
                    code.push_str(&format!("{}ritual {} {{\n", indent_str, name));
                }
                
                for item in items {
                    self.generate_node(item, code, if name == "root" { indent } else { indent + 1 });
                }
                
                if name != "root" {
                    code.push_str(&format!("{}}}\n\n", indent_str));
                }
            }
            
            AstNode::Function { name, params, return_type, body, is_async, visibility } => {
                let vis = self.visibility_keyword(*visibility);
                let asyncness = if *is_async { "weave " } else { "" };
                
                let is_ritual = name.starts_with("ritual_");
                let is_sigil = name.starts_with("sigil_");
                
                let keyword = if is_ritual {
                    "ritual"
                } else if is_sigil {
                    "sigil"
                } else {
                    "sigil" // Default to sigil
                };
                
                let clean_name = name
                    .strip_prefix("ritual_")
                    .or_else(|| name.strip_prefix("sigil_"))
                    .unwrap_or(name);
                
                let params_str = params.iter()
                    .map(|p| format!("{}: {}", p.name, self.type_to_fuxyez(&p.ty)))
                    .collect::<Vec<_>>()
                    .join(", ");
                
                let return_str = if let Some(ty) = return_type {
                    format!(" -> {}", self.type_to_fuxyez(ty))
                } else {
                    String::new()
                };
                
                code.push_str(&format!("{}{}{}{} {}({}){} {{\n",
                    indent_str, vis, asyncness, keyword, clean_name, params_str, return_str));
                
                if body.is_empty() {
                    code.push_str(&format!("{}    collapse {{}}\n", indent_str));
                } else {
                    for stmt in body {
                        self.generate_node(stmt, code, indent + 1);
                    }
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
            
            AstNode::Struct { name, fields, visibility } => {
                let vis = self.visibility_keyword(*visibility);
                let is_lattice = name.starts_with("Lattice");
                
                let clean_name = name.strip_prefix("Lattice").unwrap_or(name);
                
                code.push_str(&format!("{}{}lattice {} {{\n", indent_str, vis, clean_name));
                
                for field in fields {
                    let field_vis = self.visibility_keyword(field.visibility);
                    code.push_str(&format!("{}    {}{}: {},\n",
                        indent_str, field_vis, field.name, self.type_to_fuxyez(&field.ty)));
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
            
            AstNode::Enum { name, variants, visibility } => {
                let vis = self.visibility_keyword(*visibility);
                
                code.push_str(&format!("{}{}echo {} {{\n", indent_str, vis, name));
                
                for variant in variants {
                    code.push_str(&format!("{}    {},\n", indent_str, variant.name));
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
            
            AstNode::VarDecl { name, ty, value, is_mutable } => {
                let mutability = if *is_mutable { "mut " } else { "" };
                let ty_hint = if let Some(t) = ty {
                    format!(": {}", self.type_to_fuxyez(t))
                } else {
                    String::new()
                };
                
                code.push_str(&format!("{}let {}{}{}", indent_str, mutability, name, ty_hint));
                
                if let Some(val) = value {
                    code.push_str(" = ");
                    self.generate_node(val, code, 0);
                }
                
                code.push_str(";\n");
            }
            
            AstNode::Literal(lit) => {
                match lit {
                    Literal::String(s) => code.push_str(&format!("\"{}\"", s)),
                    Literal::Int(i) => code.push_str(&i.to_string()),
                    Literal::Float(f) => code.push_str(&f.to_string()),
                    Literal::Bool(b) => code.push_str(if *b { "true" } else { "false" }),
                    Literal::Null => code.push_str("null"),
                    _ => code.push_str("()"),
                }
            }
            
            AstNode::Comment(text) => {
                code.push_str(&format!("{}// {}\n", indent_str, text));
            }
            
            _ => {
                // TODO: Implement remaining node types
            }
        }
    }
    
    fn visibility_keyword(&self, vis: Visibility) -> &'static str {
        match vis {
            Visibility::Public => "pub ",
            Visibility::Private => "",
            Visibility::Protected => "pub(sacred) ",
            Visibility::Internal => "pub(ritual) ",
        }
    }
    
    fn type_to_fuxyez(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "i32".to_string(),
            Type::Float => "f64".to_string(),
            Type::String => "String".to_string(),
            Type::Bool => "bool".to_string(),
            Type::Void => "()".to_string(),
            Type::Named(n) => n.clone(),
            Type::Array(inner) => format!("Vec<{}>", self.type_to_fuxyez(inner)),
            Type::Tuple(types) => {
                let inner = types.iter()
                    .map(|t| self.type_to_fuxyez(t))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({})", inner)
            }
            Type::Option(inner) => format!("Option<{}>", self.type_to_fuxyez(inner)),
            Type::Generic { name, params } => {
                let params_str = params.iter()
                    .map(|t| self.type_to_fuxyez(t))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}<{}>", name, params_str)
            }
            Type::Unknown => "unknown".to_string(),
            _ => "()".to_string(),
        }
    }
}

impl Default for FuxyezCodegen {
    fn default() -> Self {
        Self::new()
    }
}