//! WebAssembly (WAT) Code Generator

use anyhow::Result;
use crate::{
    ast::*,
    core::context::TransmutationContext,
};

pub struct WasmGenerator;

impl WasmGenerator {
    pub fn new() -> Self {
        Self
    }
    
    pub fn generate_wat(&self, ast: &UniversalAst, _context: &TransmutationContext) -> Result<String> {
        let mut wat = String::new();
        
        wat.push_str(";; Generated by FUTE - Fuxyez Universal Transmutation Engine\n\n");
        wat.push_str("(module\n");
        
        // Generate memory section
        wat.push_str("  (memory (export \"memory\") 1)\n\n");
        
        // Generate function exports
        self.generate_functions(&ast.root, &mut wat);
        
        wat.push_str(")\n");
        
        Ok(wat)
    }
    
    fn generate_functions(&self, node: &AstNode, wat: &mut String) {
        match node {
            AstNode::Module { items, .. } => {
                for item in items {
                    self.generate_functions(item, wat);
                }
            }
            
            AstNode::Function { name, params, return_type, .. } => {
                let param_str = params.iter()
                    .map(|p| format!("(param ${} {})", p.name, self.wasm_type(&p.ty)))
                    .collect::<Vec<_>>()
                    .join(" ");
                
                let result_str = if let Some(ty) = return_type {
                    format!(" (result {})", self.wasm_type(ty))
                } else {
                    String::new()
                };
                
                wat.push_str(&format!("  (func ${}(export \"{}\") {}{}\n",
                    name, name, param_str, result_str));
                
                // Simple stub body
                if return_type.is_some() {
                    // Return default value
                    wat.push_str("    i32.const 0\n");
                }
                
                wat.push_str("  )\n\n");
            }
            
            _ => {}
        }
    }
    
    fn wasm_type(&self, ty: &Type) -> &'static str {
        match ty {
            Type::Int | Type::Bool => "i32",
            Type::Float => "f64",
            _ => "i32", // Default to i32 for complex types
        }
    }
}

impl Default for WasmGenerator {
    fn default() -> Self {
        Self::new()
    }
}