{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "aurafs.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "aurafs.name" . }}
    app.kubernetes.io/part-of: aurphyx
{{- end }}
