{{- if .Values.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ include "aurafs.namespace" . }}
type: kubernetes.io/tls
stringData:
  tls.crt: "{{ .Values.tls.cert }}"
  tls.key: "{{ .Values.tls.key }}"
{{- end }}
