apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurafs.fullname" . }}-api
  namespace: {{ include "aurafs.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "aurafs.name" . }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.api.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: http
      port: {{ .Values.api.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "aurafs.name" . }}
    app.kubernetes.io/component: api
