package org.aurphyx.vasp

/**
 * DSP / NLP / catalog inputs for [VaspScoringEngine].
 *
 * Required fields are the Phase I/II measurements the engine always reads.
 * Catalog-only fields stay null / empty — the engine emits `null`, `[]`, or
 * `"unknown"` and does not invent samples, era, tribe, or lyrics.
 */
data class RawAnalysis(
    val bpm: Double,
    val attackMs: Double,
    val centroidHz: Double,
    val keyMode: String,
    val sentimentScore: Double,
    val rmsAmplitude: Double,
    val dominantFreqHz: Double,
    val title: String? = null,
    val artist: String? = null,
    val isrc: String? = null,
    val sourceDna: String? = null,
    val keySignature: String? = null,
    val bpmPerceived: String? = null,
    val grooveQuantization: String? = null,
    val timeSignature: String? = null,
    val sectionalMarkers: List<String> = emptyList(),
    val mixWindowIndex: Double? = null,
    val breakdownDepth: Double? = null,
    val syncopationIndex: Double? = null,
    val ghostNoteDensity: Double? = null,
    val subDominant: Double? = null,
    val midForward: Double? = null,
    val airBrilliance: Double? = null,
    val spectralSaturation: Double? = null,
    val fidelityScore: String? = null,
    val dynamicRangeLra: Double? = null,
    val spatialWidth: String? = null,
    val textureSurface: String? = null,
    val textureArtifacts: String? = null,
    val moodStability: String? = null,
    val catharsisPotential: Double? = null,
    val nostalgiaTrigger: Double? = null,
    val buildUpVelocity: Double? = null,
    val resolutionState: String? = null,
    val secondaryHex: String? = null,
    val brightnessFloor: Double? = null,
    val brightnessCeiling: Double? = null,
    val strobeTrigger: Double? = null,
    val fadeRate: String? = null,
    val fogDensity: Double? = null,
    val laserCompatibility: Boolean? = null,
    val visualNoise: String? = null,
    val breathRate: Double? = null,
    val sway: Double? = null,
    val chordComplexity: String? = null,
    val dissonanceRating: Double? = null,
    val rangeSpan: Double? = null,
    val hookStrength: Double? = null,
    val melodicMotion: String? = null,
    val referencePitch: String? = null,
    val microtonality: String? = null,
    val explicitFilter: String? = null,
    val topicClusters: List<String> = emptyList(),
    val narrativeArc: String? = null,
    val vocalPosition: String? = null,
    val deliveryStyle: String? = null,
    val vocalProcessing: String? = null,
    val primaryLanguage: String? = null,
    val dialectSlang: String? = null,
    val macroSetting: String? = null,
    val microActivity: String? = null,
    val socialSetting: String? = null,
    val functionalGoal: String? = null,
    val timeOfDay: String? = null,
    val weather: String? = null,
    val temperature: String? = null,
    val releaseDate: String? = null,
    val culturalEra: String? = null,
    val timelessnessScore: Double? = null,
    val sampleLineage: List<String> = emptyList(),
    val interpolation: List<String> = emptyList(),
    val genreTree: String? = null,
    val subcultureId: String? = null,
    val authenticityScore: Double? = null,
    val viralVelocity: String? = null,
) {
    companion object {
        /** Mock representing "After Dark" by Mr.Kitty — same fixture as the Python engine. */
        fun afterDark() = RawAnalysis(
            title = "After Dark",
            artist = "Mr.Kitty",
            bpm = 135.0,
            attackMs = 45.0,
            centroidHz = 2200.0,
            keyMode = "Minor",
            sentimentScore = -0.2,
            rmsAmplitude = 0.75,
            dominantFreqHz = 3000.0,
        )
    }
}
