apiVersion: v1
kind: Namespace
metadata:
  name: aurphyx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: afs-api
  namespace: aurphyx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: afs-api
  template:
    metadata:
      labels:
        app: afs-api
    spec:
      containers:
      - name: afs-api
        image: aurphyx/afs-api:v25.0.0
        ports:
        - containerPort: 8080
