//! Python Code Generator

use anyhow::Result;
use crate::{
    ast::*,
    core::context::TransmutationContext,
};

pub struct PythonGenerator;

impl PythonGenerator {
    pub fn new() -> Self {
        Self
    }
    
    pub fn generate_code(&self, ast: &UniversalAst, _context: &TransmutationContext) -> Result<String> {
        let mut code = String::new();
        
        code.push_str("# Generated by FUTE - Fuxyez Universal Transmutation Engine\n\n");
        
        self.generate_node(&ast.root, &mut code, 0);
        
        Ok(code)
    }
    
    fn generate_node(&self, node: &AstNode, code: &mut String, indent: usize) {
        let indent_str = "    ".repeat(indent);
        
        match node {
            AstNode::Module { items, .. } => {
                for item in items {
                    self.generate_node(item, code, indent);
                }
            }
            
            AstNode::Function { name, params, return_type, body, is_async, .. } => {
                let asyncness = if *is_async { "async " } else { "" };
                let params_str = params.iter()
                    .map(|p| {
                        if let Some(ty) = &p.ty.as_python_hint() {
                            format!("{}: {}", p.name, ty)
                        } else {
                            p.name.clone()
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                
                let return_str = if let Some(ty) = return_type {
                    format!(" -> {}", ty.as_python_hint().unwrap_or("None".to_string()))
                } else {
                    String::new()
                };
                
                code.push_str(&format!("{}{}def {}({}){}:\n", 
                    indent_str, asyncness, name, params_str, return_str));
                
                if body.is_empty() {
                    code.push_str(&format!("{}    pass\n\n", indent_str));
                } else {
                    for stmt in body {
                        self.generate_node(stmt, code, indent + 1);
                    }
                    code.push('\n');
                }
            }
            
            AstNode::Class { name, fields, methods, base_class, .. } => {
                let base = if let Some(b) = base_class {
                    format!("({})", b)
                } else {
                    String::new()
                };
                
                code.push_str(&format!("{}class {}{}:\n", indent_str, name, base));
                
                if fields.is_empty() && methods.is_empty() {
                    code.push_str(&format!("{}    pass\n\n", indent_str));
                } else {
                    for field in fields {
                        code.push_str(&format!("{}    {}: {}\n", 
                            indent_str, field.name, 
                            field.ty.as_python_hint().unwrap_or("Any".to_string())));
                    }
                    
                    for method in methods {
                        self.generate_node(method, code, indent + 1);
                    }
                    code.push('\n');
                }
            }
            
            AstNode::VarDecl { name, ty, value, .. } => {
                let ty_hint = if let Some(t) = ty {
                    format!(": {}", t.as_python_hint().unwrap_or("Any".to_string()))
                } else {
                    String::new()
                };
                
                if let Some(val) = value {
                    code.push_str(&format!("{}{}{} = ", indent_str, name, ty_hint));
                    self.generate_node(val, code, 0);
                    code.push('\n');
                } else {
                    code.push_str(&format!("{}{}{}\n", indent_str, name, ty_hint));
                }
            }
            
            AstNode::Literal(lit) => {
                match lit {
                    Literal::String(s) => code.push_str(&format!("\"{}\"", s)),
                    Literal::Int(i) => code.push_str(&i.to_string()),
                    Literal::Float(f) => code.push_str(&f.to_string()),
                    Literal::Bool(b) => code.push_str(if *b { "True" } else { "False" }),
                    Literal::Null => code.push_str("None"),
                    _ => code.push_str("None"),
                }
            }
            
            _ => {
                // TODO: Implement other node types
            }
        }
    }
}

impl Default for PythonGenerator {
    fn default() -> Self {
        Self::new()
    }
}

// Extension trait for Python type hints
trait PythonTypeHint {
    fn as_python_hint(&self) -> Option<String>;
}

impl PythonTypeHint for Type {
    fn as_python_hint(&self) -> Option<String> {
        Some(match self {
            Type::Int => "int".to_string(),
            Type::Float => "float".to_string(),
            Type::String => "str".to_string(),
            Type::Bool => "bool".to_string(),
            Type::Void => "None".to_string(),
            Type::Named(n) => n.clone(),
            Type::Array(inner) => format!("list[{}]", inner.as_python_hint()?),
            Type::Option(inner) => format!("Optional[{}]", inner.as_python_hint()?),
            _ => "Any".to_string(),
        })
    }
}