FROM node:18-alpine as builder

WORKDIR /app

COPY web/package*.json ./
RUN npm ci

COPY web ./
RUN npm run build

# Runtime stage
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "start"]

