//! Universal AST to Rust code generator

use anyhow::Result;
use crate::{
    ast::*,
    core::context::TransmutationContext,
};

pub struct RustGenerator;

impl RustGenerator {
    pub fn new() -> Self {
        Self
    }
    
    pub fn generate_code(&self, ast: &UniversalAst, _context: &TransmutationContext) -> Result<String> {
        let mut code = String::new();
        
        code.push_str("// Generated by FUTE - Fuxyez Universal Transmutation Engine\n\n");
        
        self.generate_node(&ast.root, &mut code, 0);
        
        Ok(code)
    }
    
    fn generate_node(&self, node: &AstNode, code: &mut String, indent: usize) {
        let indent_str = "    ".repeat(indent);
        
        match node {
            AstNode::Module { name, items } => {
                if name != "root" {
                    code.push_str(&format!("{}mod {} {{\n", indent_str, name));
                }
                
                for item in items {
                    self.generate_node(item, code, if name == "root" { indent } else { indent + 1 });
                }
                
                if name != "root" {
                    code.push_str(&format!("{}}}\n\n", indent_str));
                }
            }
            
            AstNode::Function { name, params, return_type, body, is_async, visibility } => {
                let vis = self.generate_visibility(*visibility);
                let asyncness = if *is_async { "async " } else { "" };
                let params_str = params.iter()
                    .map(|p| format!("{}: {}", p.name, self.generate_type(&p.ty)))
                    .collect::<Vec<_>>()
                    .join(", ");
                
                let return_str = if let Some(ty) = return_type {
                    format!(" -> {}", self.generate_type(ty))
                } else {
                    String::new()
                };
                
                code.push_str(&format!("{}{}{}fn {}({}){} {{\n", 
                    indent_str, vis, asyncness, name, params_str, return_str));
                
                for stmt in body {
                    self.generate_node(stmt, code, indent + 1);
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
            
            AstNode::Struct { name, fields, visibility } => {
                let vis = self.generate_visibility(*visibility);
                code.push_str(&format!("{}{}struct {} {{\n", indent_str, vis, name));
                
                for field in fields {
                    let field_vis = self.generate_visibility(field.visibility);
                    code.push_str(&format!("{}    {}{}: {},\n", 
                        indent_str, field_vis, field.name, self.generate_type(&field.ty)));
                }
                
                code.push_str(&format!("{}}}\n\n", indent_str));
            }
            
            _ => {
                // TODO: Implement other node types
            }
        }
    }
    
    fn generate_visibility(&self, vis: Visibility) -> &'static str {
        match vis {
            Visibility::Public => "pub ",
            Visibility::Private => "",
            Visibility::Protected => "pub(crate) ",
            Visibility::Internal => "pub(super) ",
        }
    }
    
    fn generate_type(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "i32".to_string(),
            Type::Float => "f64".to_string(),
            Type::String => "String".to_string(),
            Type::Bool => "bool".to_string(),
            Type::Void => "()".to_string(),
            Type::Named(name) => name.clone(),
            Type::Array(inner) => format!("Vec<{}>", self.generate_type(inner)),
            Type::Option(inner) => format!("Option<{}>", self.generate_type(inner)),
            Type::Unknown => "/* unknown */".to_string(),
            _ => "/* complex type */".to_string(),
        }
    }
}

impl Default for RustGenerator {
    fn default() -> Self {
        Self::new()
    }
}